title: Casa Ronnete
views:
  - title: Resumen
    path: resumen
    theme: ''
    badges:
      - entity: person.watchout
      - entity: person.mirian
    cards:
      - type: custom:pvpc-hourly-pricing-card
        entity: sensor.esios_pvpc
      - type: entities
        entities:
          - entity: light.habitacion
          - entity: light.habitacion_azul
          - entity: switch.shelly_shsw_1_483fda822ac9
          - entity: switch.shelly_shsw_1_483fda82a8c9
          - entity: switch.shelly_shsw_1_483fda82b789
          - entity: switch.lavadora_1
          - entity: switch.lampara_del_salon_1
          - entity: switch.lavavajillas_1
      - type: custom:weather-card
        entity: weather.aemet_daily
        number_of_forecasts: '5'
        name: AEMET
      - type: custom:scheduler-card
        include:
          - switch.smart_switch_20072932809313251h5648e1e928b7fb_outlet
        exclude: []
      - type: custom:xiaomi-vacuum-map-card
        title: Xiaomi Vacuum Map Card
        language: es
        preset_name: Live map
        entity: vacuum.pumba
        map_source:
          camera: camera.xiaomi_cloud_map_extractor
        calibration_source:
          camera: true
      - type: custom:mini-media-player
        entity: media_player.spotify_sergiorami
        icon: mdi:spotify
        artwork: cover
        hide:
          volume: true
          source: true
          power_state: false
      #- type: 'custom:spotify-card'
        #account: <optional> which account to use for spotcast. Defaults to "default"
        #height: <optional pixels height for the playlist element. If content is larger scrolling will be enabled>
        #limit: <optional number of playlists to retrieve (default 10)>
        #device: <optional name of a device to pre-select>
        #playlist_type: <optional featured|discover-weekly> Change type of playlists shown. Default are your normal playlists.
        #always_play_random_song: <optional true> Set to start playlists from a random song.
        #country_code: <optional country code to show featured playlist relevent to a particular country. https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 >
        #hide_warning: <optional true> Hide warnings if they are displayed.
        #name: <optional name> Custom title. Leave empty to hide.
        #display_style: <optional Grid> Change default display style.
        #grid_covers_per_row: <optional number> Number of covers per row (default 3) in Grid-view.
        #spotify_entity: <optional> Name of your spotify media player entity if it doesn't start with "spotify"
        #default_device: <optional> Name of your spotify connect or chromecast device, e.g. "Kitchen"
        #filter_devices: <optional Array> Hides devices which matches any array entry. The entries have to be regular expressions and are matched against the full device-name. The following are examples
        #  - .*room <hides all devices ending with room>
        #  - bath.*,kids.* <hides all devices which start with bath or kids>
        #known_connect_devices: <optional> List of known Spotify Connect devices, see [Known Spotify Connect devices](Known-Spotify-Connect-devices) section
        #  - id: The Spotify Connect device id
        #    name: The name of the device
        #    entity_id: <optional> The Home Assistant media player entity id of this device (e.g. from Sonos integration)
  - title: Plano
    icon: mdi:floor-plan
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:floorplan-card
                full_height: true
                full_width: true
                config:
                  image: /local/floorplan/home_v2.svg
                  stylesheet: /local/floorplan/home_v1.css
                  defaults:
                    hover_action: hover-info
                    tap_action: more-info
                  rules:
                    - entity: switch.shelly_shsw_1_483fda822ac9
                      element: light.pasillo
                      tap_action: toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
                    - entity: switch.shelly_shsw_1_483fda82a8c9
                      element: light.sofa
                      tap_action: toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
                    - entity: switch.shelly_shsw_1_483fda82b789
                      element: light.salon_mesa
                      tap_action: toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
                    - entity: switch.lampara_del_salon_1
                      element: switch.lampara_salon
                      tap_action: toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
                    - entity: light.habitacion
                      element: light.habitacion
                      tap_action: toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
                    - entity: light.habitacion_azul
                      element: light.habitacion_azul
                      tap_action: toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
                    - entity: sensor.ble_temperature_salon
                      element: sensor.temperatura_salon
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data:
                          text: |
                            >
                            return entity.state + " ºC";
                    - entity: sensor.ble_temperature_dormitorio
                      element: sensor.temperatura_dormitorio
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data:
                          text: |
                            >
                            return entity.state + " ºC";
                    - entity: sensor.ble_temperature_habitacion
                      element: sensor.temperatura_habitacion
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data:
                          text: |
                            >
                            return entity.state + " ºC";
                    - entity: sensor.ble_temperature_gimnasio
                      element: sensor.temperatura_gimnasio
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data:
                          text: |
                            >
                            return entity.state + " ºC";
