version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check config
          command: |
            mv secrets-dummy.yaml secrets.yaml
            mv google-assistant-details-dummy.json google-assistant-details.json
            python3.9 -m venv .
            source bin/activate
            pip3 install homeassistant
            python -m homeassistant --config . --script check_config --info all