version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check config
          command: |
            mv secrets-dummy.yaml secrets.yaml
            python3.6 -m venv .
            source bin/activate
            pip3 install --pre --upgrade homeassistant
            hass -c . --script check_config --info all